### ISSUE TITLE
Get full results from AIN Wallet's sendTransaction API

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-js#181]
We need to request AIN Wallet's owner to make sendTransaction API return full results, and update related logic in ain-js appropriately.

Related PRs:
- https://github.com/ainft-team/ainft-js/pull/269
- https://bitbucket.org/comcomai/ain-connect-extension/pull-requests/47/return-all-sendtransaction-result?link_source=email

**Comment by jiyoung-an** [comment]
I checked that AIN wallet's owner resolved issue!
![image](https://github.com/ainblockchain/ain-js/assets/122012800/107f47ba-c1d2-48e0-b96c-aa69216a08e7)

**Comment by platfowner** [comment]
Thanks for checking. @jiyoung-an  Now can this code be uncommented? https://github.com/ainft-team/ainft-js/blob/develop/src/utils/util.ts#L51

**Comment by platfowner** [comment]
Just checked that the code is uncommented:
https://github.com/ainft-team/ainft-js/pull/273
