### ISSUE TITLE
Can't handle 'sendTransaction' error

### ISSUE THREAD

**Issue by pengin7384** [ainblockchain/ain-js#9]
![image](https://user-images.githubusercontent.com/32831939/73633219-7849c180-46a1-11ea-874c-d0c921577849.png)
When I use 'sendTransaction' without adding wallet, 'sendTransaction' throws 'Error: You need to specify the address or set defaultAccount.'.
But I can't catch it.

Code
```
try {
  ain.sendTransaction({
        operation: {
          type: 'SET_VALUE',
          ref: 'apps/afan/popular_posts',
          value: null,
        }
      },
  ).catch(err => {
    console.log(err);
  });
} catch (err) {
  console.log(err);
}
```

**Comment by liayoo** [comment]
Closing since this issue has been fixed in https://github.com/ainblockchain/ain-js/pull/10
